# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

In [1]:
# Your code here
import numpy as np
import pandas as pd

url ="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
insurance = pd.read_csv(url)


insurance.shape

(4008, 11)

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [2]:
# Your code here
display(insurance)

insurance.info()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 417.4 KB

In [3]:
# Your code here
insurance.columns = (
    insurance.columns
    .str.strip()        # eltávolitja a felesleges szóközöket, whitespace-eket, tab-okat, stb a columnname-ek elején és végén
    .str.lower()        # a nagybetűket átalakitja kicsire
    .str.replace(" ", "_")    # az elsőként  megjelölt karaktert átcseréli a másodikra
    
)

insurance = insurance.rename(columns={
    "st": "state"
})

display(insurance.columns.tolist())

['customer',
 'state',
 'gender',
 'education',
 'customer_lifetime_value',
 'income',
 'monthly_premium_auto',
 'number_of_open_complaints',
 'policy_type',
 'vehicle_class',
 'total_claim_amount']

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [4]:
# Your code here


insurance.info()
print("\n")
display(insurance["state"].unique())
# display(insurance["state"].nunique())


old_states = insurance['state'].copy()

# ['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',
       # 'Cali',         'AZ',         'WA',          nan]

insurance['state'] = insurance['state'].replace({
    'Cali': 'California',
    'AZ': 'Arizona',
    'WA': 'Washington'
})

print("\n")
display(insurance["state"].unique())

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   str
 1   state                      1071 non-null   str
 2   gender                     954 non-null    str
 3   education                  1071 non-null   str
 4   customer_lifetime_value    1068 non-null   str
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   str
 8   policy_type                1071 non-null   str
 9   vehicle_class              1071 non-null   str
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 417.4 KB

<ArrowStringArray>
['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',
       'Cali',         'AZ',         'WA',          nan]
Length: 9, dtype: str

<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan]
Length: 6, dtype: str

In [5]:
# Your code here

print("\n")
display(insurance['gender'].unique())

old_genders = insurance['gender'].copy()

# [nan, 'F', 'M', 'Femal', 'Male', 'female']

insurance['gender'] = insurance['gender'].replace({
    'Femal': 'F',
    'Male': 'M',
    'female': 'F'
 })

print("\n")
display(insurance['gender'].unique())

<ArrowStringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str

<ArrowStringArray>
[nan, 'F', 'M']
Length: 3, dtype: str

In [6]:
# Your code here

print("\n")
display(insurance['education'].unique())

old_education = insurance['education'].copy()

# [              'Master',             'Bachelor', 'High School or Below',
# 'College',            'Bachelors',               'Doctor',
                    # nan]

insurance['education'] = insurance['education'].replace({
    'Bachelors': 'Bachelor'
})

print("\n")
display(insurance['education'].unique())

<ArrowStringArray>
[              'Master',             'Bachelor', 'High School or Below',
              'College',            'Bachelors',               'Doctor',
                    nan]
Length: 7, dtype: str

<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor', nan]
Length: 6, dtype: str

In [7]:
# Your code here


print("\n")
display(insurance['customer_lifetime_value'].unique())

old_customer_lifetime_value = insurance['customer_lifetime_value'].copy()

# [              'Master',             'Bachelor', 'High School or Below',
# 'College',            'Bachelors',               'Doctor',
                    # nan]

insurance['customer_lifetime_value'] = insurance['customer_lifetime_value'].str.replace('%', '', regex=False)


print("\n")
display(insurance['customer_lifetime_value'].unique())

<ArrowStringArray>
[          nan,  '697953.59%', '1288743.17%',  '764586.18%',  '536307.65%',
  '825629.78%',  '538089.86%',  '721610.03%', '2412750.40%',  '738817.81%',
 ...
  '943891.56%', '1050677.17%',  '421391.86%',  '477368.64%',  '544142.01%',
  '284226.69%',  '305955.03%', '2031499.76%',  '323912.47%',  '899704.02%']
Length: 1028, dtype: str

<ArrowStringArray>
[         nan,  '697953.59', '1288743.17',  '764586.18',  '536307.65',
  '825629.78',  '538089.86',  '721610.03', '2412750.40',  '738817.81',
 ...
  '943891.56', '1050677.17',  '421391.86',  '477368.64',  '544142.01',
  '284226.69',  '305955.03', '2031499.76',  '323912.47',  '899704.02']
Length: 1028, dtype: str

In [8]:
# Your code here
# in vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"

print("\n")
display(insurance['vehicle_class'].unique())

old_vehicle_class = insurance['vehicle_class'].copy()

# ['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
# 'Sports Car',    'Luxury Car',             nan]

insurance['vehicle_class'] = insurance['vehicle_class'].replace({
    'Sports Car': 'Luxury',
    'Luxury SUV': 'Luxury',
    'Luxury Car': 'Luxury'
})

print("\n")
display(insurance['vehicle_class'].unique())

<ArrowStringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car',             nan]
Length: 7, dtype: str

<ArrowStringArray>
['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan]
Length: 5, dtype: str

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [9]:
# Your code here

insurance.info()

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   str
 1   state                      1071 non-null   str
 2   gender                     954 non-null    str
 3   education                  1071 non-null   str
 4   customer_lifetime_value    1068 non-null   str
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   str
 8   policy_type                1071 non-null   str
 9   vehicle_class              1071 non-null   str
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 416.7 KB

In [10]:
# Your code here
# Hint:
# Customer lifetime value should be numeric

insurance['customer_lifetime_value'] = insurance['customer_lifetime_value'].astype(float)
insurance.info()

# Number of open complaints has an incorrect format. 
# Look at the different values it takes with unique() and take the middle value. 
# As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use split() to deal 
# with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.


print(insurance['number_of_open_complaints'].unique())


extracted_values = (
    insurance['number_of_open_complaints']
    .astype(str)
    .str.split('/')
    .str[1]
)

insurance['number_of_open_complaints'] = (
    pd.to_numeric(extracted_values, errors='coerce')
    .astype('Int64')
)


print("\nBefore:", insurance['number_of_open_complaints'].unique())
print("\nAfter unique values:", insurance['number_of_open_complaints'].unique())
print("\nAfter data type:", insurance['number_of_open_complaints'].dtype)

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   str
 1   state                      1071 non-null   str
 2   gender                     954 non-null    str
 3   education                  1071 non-null   str
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   str
 8   policy_type                1071 non-null   str
 9   vehicle_class              1071 non-null   str
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(4), str(7)
memory usage: 406.6 KB
<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

Before: <IntegerArray>
[0, 2, 1, 3, 5, 4, <NA>]
Length: 7, dtype: Int64

After unique values: <IntegerArray>
[0, 2, 1, 3, 5, 4, <NA>]
Length: 7, dtype: Int64

After data type: Int64

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [14]:
print("Missing values per column:")
print(insurance.isnull().sum())

Missing values per column:
customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [13]:
# Since 'customer' appears to be a unique value, I discard the row if it is empty.

insurance = insurance.dropna(subset=['customer'])
print(insurance.isnull().sum())

customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [14]:
# In the case of gender, instead of using false data, I introduced a new category: U as unknown

insurance['gender'] = insurance['gender'].fillna('U')


print(insurance['gender'].value_counts(dropna=False))

gender
F    502
M    452
U    117
Name: count, dtype: int64

In [15]:
# In the case of gender, instead of using false data, I introduced a new category: U as unknown

clv_median = insurance['customer_lifetime_value'].median()
insurance['customer_lifetime_value'] = insurance['customer_lifetime_value'].fillna(clv_median)

print(insurance.isnull().sum())

numeric_cols = insurance.select_dtypes(include=['float64', 'int64', 'Int64']).columns

for col in numeric_cols:
    insurance[col] = insurance[col].round().astype('Int64')

print(insurance.dtypes)

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64
customer                       str
state                          str
gender                         str
education                      str
customer_lifetime_value      Int64
income                       Int64
monthly_premium_auto         Int64
number_of_open_complaints    Int64
policy_type                    str
vehicle_class                  str
total_claim_amount           Int64
dtype: object

In [20]:
display(insurance)

insurance.info()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,U,Master,588174,0,1000,0,Personal Auto,Four-Door Car,3
1,QZ44356,Arizona,F,Bachelor,697954,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586,0,106,0,Corporate Auto,SUV,530
4,GA49547,Washington,M,High School or Below,536308,36357,68,0,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955,38644,78,1,Personal Auto,Four-Door Car,361
1067,VJ51327,California,F,High School or Below,2031500,63209,102,2,Personal Auto,SUV,207
1068,GS98873,Arizona,F,Bachelor,323912,16061,88,0,Personal Auto,Four-Door Car,634
1069,CW49887,California,F,Master,462680,79487,114,0,Special Auto,SUV,547
1070,MY31220,California,F,College,899704,54230,112,0,Personal Auto,Two-Door Car,538

<class 'pandas.DataFrame'>
RangeIndex: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   str
 1   state                      1071 non-null   str
 2   gender                     1071 non-null   str
 3   education                  1071 non-null   str
 4   customer_lifetime_value    1071 non-null   Int64
 5   income                     1071 non-null   Int64
 6   monthly_premium_auto       1071 non-null   Int64
 7   number_of_open_complaints  1071 non-null   Int64
 8   policy_type                1071 non-null   str
 9   vehicle_class              1071 non-null   str
 10  total_claim_amount         1071 non-null   Int64
dtypes: Int64(5), str(6)
memory usage: 150.5 KB

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [17]:
# Your code here

duplicates_count = insurance.duplicated().sum()
print(f"Number of duplicated rows before cleaning: {duplicates_count}")

insurance = insurance.drop_duplicates(keep='first').reset_index(drop=True)

print(f"Number of duplicated rows after cleaning: {insurance.duplicated().sum()}")

insurance = insurance.reset_index(drop=True)

display(insurance)

insurance.info()

Number of duplicated rows before cleaning: 0
Number of duplicated rows after cleaning: 0

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,U,Master,588174,0,1000,0,Personal Auto,Four-Door Car,3
1,QZ44356,Arizona,F,Bachelor,697954,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586,0,106,0,Corporate Auto,SUV,530
4,GA49547,Washington,M,High School or Below,536308,36357,68,0,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955,38644,78,1,Personal Auto,Four-Door Car,361
1067,VJ51327,California,F,High School or Below,2031500,63209,102,2,Personal Auto,SUV,207
1068,GS98873,Arizona,F,Bachelor,323912,16061,88,0,Personal Auto,Four-Door Car,634
1069,CW49887,California,F,Master,462680,79487,114,0,Special Auto,SUV,547
1070,MY31220,California,F,College,899704,54230,112,0,Personal Auto,Two-Door Car,538

<class 'pandas.DataFrame'>
RangeIndex: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   str
 1   state                      1071 non-null   str
 2   gender                     1071 non-null   str
 3   education                  1071 non-null   str
 4   customer_lifetime_value    1071 non-null   Int64
 5   income                     1071 non-null   Int64
 6   monthly_premium_auto       1071 non-null   Int64
 7   number_of_open_complaints  1071 non-null   Int64
 8   policy_type                1071 non-null   str
 9   vehicle_class              1071 non-null   str
 10  total_claim_amount         1071 non-null   Int64
dtypes: Int64(5), str(6)
memory usage: 150.5 KB

In [18]:
# Your code here

insurance.to_csv('cleaned_insurance_data.csv', index=False)
print("\nThe cleaned and formatted dataset saved:'cleaned_insurance_data.csv'")

The cleaned and formatted dataset saved:'cleaned_insurance_data.csv'

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [ ]:
# Your code here